modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="hpindicator"
version="${file.jarVersion}"
displayName="HP Indicator"
authors="hpindicator"
description='''
Shows real-time player health above their heads.
Works on invisible players. Client-side only.
'''

[[dependencies.hpindicator]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.hpindicator]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="CLIENT"
